program: main.py
method: random
metric:
  name: 'task_mean/acc'
  goal: maximize
parameters:
  lr:
    values: [0.001, 0.002, 0.003, 0.005, 0.01, 0.05]
  dataset:
    values: ["cifar100", "imagenetr", "cub", "dil_imagenetr", "imageneta", "vtab", "cars", "omnibenchmark", "limited_domainnet"] # kein cddb
  finetune_method:
    values: ["vpt", "adapter"] # ssf fehlt noch und funktioniert auch noch nicht
  finetune_epochs:
    values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  moe_max_experts:
    values: [1, 2, 3, 4, 5, 8, 10]
  reduce_dataset:
    values: [1]
  T:
    values: [10]
  classification:
    values: ['average', "bayesian"]
  backbone:
    values: ["vit_base_patch16_224", "vit_base_patch16_224_in21k"]
  sweep_logging:
    values: [True]