program: main.py
method: grid
metric:
  name: 'task_mean/acc'
  goal: maximize
parameters:
  lr:
    values: [0.05]
  dataset:
    values: ["cifar100", "imagenetr", "cub", "dil_imagenetr", "imageneta", "vtab", "cars", "omnibenchmark", "limited_domainnet"] # kein cddb
  finetune_method:
    values: ["adapter"]
  finetune_epochs:
      values: [5]
  moe_max_experts:
    values: [5]
  reduce_dataset:
    values: [1]
  T:
    values: [10]
  classification:
    values: ["bayesian"]
  backbone:
    values: ["vit_base_patch16_224"]
  sweep_logging:
    values: [True]
  kd:
    values: [False]
  selection_method:
    values: ["kl_div", "inv_kl_div"]