program: main.py
method: random
metric:
  name: 'task_mean/acc'
  goal: maximize
parameters:
  lr:
    values: [0.001, 0.002, 0.003, 0.005, 0.01]
  dataset:
    values: ["imagenetr", "cub", "dil_imagenetr"]
  finetune_method:
    values: ["vpt", "adapter"] # ssf fehlt noch und funktioniert auch noch nicht
  finetune_epochs:
    values: [1, 2, 3, 4, 5, 10, 15]
  moe_max_experts:
    values: [3, 4, 5]
  reduce_dataset:
    values: [1]
  T:
    values: [25, 50, 100, 200]
  classification:
    values: ['average', "bayesian"]
  backbone:
    values: ["vit_base_patch16_224", "vit_base_patch16_224_in21k"]