program: main.py
method: random
metric:
  name: 'task_mean/acc'
  goal: maximize
parameters:
  lr:
    values: [0.002]
  dataset:
    values: ["cifar100", "imagenetr", "cub", "dil_imagenetr", "imageneta", "vtab", "cars", "omnibenchmark", "limited_domainnet"] # kein cddb
  finetune_method:
    values: ["vpt", "adapter"] # ssf fehlt noch und funktioniert auch noch nicht
  finetune_epochs:
    values: [15]
  moe_max_experts:
    values: [5]
  reduce_dataset:
    values: [1]
  T:
    values: [10]
  classification:
    values: ['average', "bayesian"]
  backbone:
    values: ["vit_base_patch16_224", "vit_base_patch16_224_in21k"]
  sweep_logging:
    values: [True]
  kd:
    values: [True, False]
  selection_method:
    values: ["eucld_dist", "inv_eucld_dist", "kl_div", "inv_kl_div", "ws_div", "inv_ws_div"]