_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.11
            "5": 0.18.7
            "8":
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
T:
    value: 10
aug_brightness_jitter:
    value: 0.1
aug_contrast_jitter:
    value: 0.1
aug_hue_jitter:
    value: 0.1
aug_normalize:
    value: false
aug_random_rotation_degree:
    value: 0
aug_resize_crop_max:
    value: 1
aug_resize_crop_min:
    value: 0.7
aug_saturation_jitter:
    value: 0.1
backbone:
    value: vit_base_patch16_224
batch_size:
    value: 48
data_root:
    value: ./local_data
dataset:
    value: cifar100
device:
    value: cpu
early_stopping:
    value: 5
finetune_epochs:
    value: 3
finetune_method:
    value: none
intralayers:
    value:
        - blocks.11
        - blocks.10
        - blocks.9
        - blocks.8
        - blocks.7
        - blocks.6
k:
    value: 6
lr:
    value: 0.003
seed:
    value: 1993
target_size:
    value: 224
wandb_entity:
    value: null
wandb_project:
    value: Local_LayUp_Test
weight_decay:
    value: 0.0005
