# num_experts in relation to T. Scaling not linearly
# Configs for one specific dataset with optimal parameters from question 1
program: main.py
method: random
metric:
  name: 'task_mean/acc'
  goal: maximize
parameters:
  lr:
    values: ["optimum_for_specific_dataset"]
  dataset:
    values: ["dataset"]
  finetune_method:
    values: ["optimal_pet_for_specific_dataset"]
  finetune_epochs:
    values: ["optimal_value_for_specific_dataset"]
  moe_max_experts:
    values: [5]
  reduce_dataset:
    values: [1]
  T:
    values: [10]
  classification:
    values: ["optimal_classification_method_for_specific_dataset"]
  backbone:
    values: ["optimal_backbone_for_specific_dataset"]
  sweep_logging:
    values: [True]
  kd:
    values: ["optimal_kd_for_specific_dataset"]
  selection_method:
    values: ["random", "eucld_dist", "inv_eucld_dist", "kl_div", "inv_kl_div", "ws_div", "inv_ws_div"]